trigger: none

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  displayName: Run Dependency Scan
  steps:

  - script: |
      npm audit --audit-level=high --json > npm-audit.json || true
      cat npm-audit.json
    displayName: 'Run npm audit'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish npm audit report'
    inputs:
      PathtoPublish: 'npm-audit.json'
      ArtifactName: 'NpmAuditReport'

  - script: |
      npm install -g retire
      retire --outputformat json --outputpath retire-report.json
    displayName: 'Run Retire.js scan'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Retire.js report'
    inputs:
      PathtoPublish: 'retire-report.json'
      ArtifactName: 'RetireJsReport'