define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
      "UnknownEnvironment": "The app is running in an unknown environment",
      "ApplicationDeadline": "Application deadline",
      "JobType": "Job Type",
      "OpportunityDetails": "Opportunity Details",
      "ProgramArea": "Program Area",
      "Department": "Department",
      "NumberOpportunities": "Number of Opportunities",
      "Duration": "Duration for opportunity",
      "WorkArrangement": "Work arrangement",
      "Location": "Location",
      "SecurityLevel": "Security level",
      "LanguageRequirements": "Language requirements",
      "Apply": "Apply",
      "Edit": "Edit",
      "Expired": "This opportunity has expired. Applications are now closed.",
      "ApplicationsClosed": "Applications Closed",
      "Delete": "Delete"
  }
});