define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
      "UnknownEnvironment": "The app is running in an unknown environment",
      "ApplicationDeadline": "Application deadline",
      "JobType": "Job type",
      "OpportunityDetails": "Opportunity details",
      "ProgramArea": "Program area",
      "Department": "Department",
      "NumberOpportunities": "Number of opportunities",
      "Duration": "Duration for opportunity",
      "WorkArrangement": "Work arrangement",
      "Location": "Location",
      "SecurityLevel": "Security level",
      "LanguageRequirements": "Language requirements",
      "Apply": "Apply",
      "Edit": "Edit",
      "Expired": "This opportunity has expired. Applications are now closed.",
      "ApplicationsClosed": "Applications closed",
      "Delete": "Delete",
      "oppDeletedTitle": "The opportunity has been deleted",
      "oppDeletedSubText": "<b>{jobTitle}</b> has been deleted. You have 30 days to contact our Support team to recover the opportunity if you change your mind. Please provide our Support team with the <b>post title</b> and <b>date that the post was deleted</b> when requesting recovery.</br></br><b>After 30 days, the opportunity will be permanently deleted.</b>",
      "contactUs": "Contact us",
      "cmHomePage": "Career marketplace homepage",
      "loading": "Loading...",
      "dialogTitle": "Delete opportunity",
      "dialogText": "<b>Are you sure you want to delete this opportunity?</b> Once deleted, you will have 30 days to contact our support team to recover the opportunity if you change your mind. After 30 days, the opportunity will be permanently deleted.",
      "cancel": "Cancel",
      "Retention": "To keep the Career Marketplace fresh and relevant, <strong>opportunity posts are automatically removed six months after the application deadline.</strong> We recommend saving a copy for your records.",
      "emailSubject": "Request to recover deleted Career Marketplace opportunity post",
      "classification": "Classification",
      "workSchedule": "Work schedule",
      "skills": "Skills"
  }
});