/* eslint-disable no-undef */
define([], function () {
    return {
        "PropertyPaneDescription": "Description",
        "BasicGroupName": "Group Name",
        "DescriptionFieldLabel": "Description Field",
        "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
        "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
        "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
        "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
        "AppSharePointEnvironment": "The app is running on SharePoint page",
        "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
        "AppOfficeEnvironment": "The app is running in office.com",
        "AppOutlookEnvironment": "The app is running in Outlook",
        "UnknownEnvironment": "The app is running in an unknown environment",
        "ApplicationDeadline": "Date limite de candidature",
        "JobType": "Type d'emploi",
        "OpportunityDetails": "Détails de la possibilité d’emploi",
        "ProgramArea": "Secteur de programme",
        "Department": "Ministère",
        "NumberOpportunities": "Nombre de possibilités d'emploi",
        "Duration": "Durée de la possibilité d’emploi",
        "WorkArrangement": "Régime de travail",
        "Location": "Lieu",
        "SecurityLevel": "Niveau de sécurité",
        "LanguageRequirements": "Exigences linguistiques",
        "Apply": "Postuler",
        "Edit": "Modifier",
        "Expired": "Possibilité expirée. Les candidatures sont maintenant fermées.",
        "ApplicationsClosed": "Candidatures fermées",
        "Delete": "Supprimer",
        "oppDeletedTitle": "L'opportunité a été supprimée",
        "oppDeletedSubText": "L’offre d’emploi <b>{jobTitle}</b> est supprimée. Si vous souhaitez la récupérer après coup, vous devrez communiquer avec l’équipe de soutien dans les 30 jours suivant sa suppression.</br></br>Vous devrez alors lui fournir le <b>titre de votre offre d’emploi</b> ainsi que sa <b>date de suppression</b>.",
        "contactUs": "Contactez nous",
        "cmHomePage": "Page d'accueil du Career Marketplace",
        "loading": "Chargement...",
        "dialogTitle": "Supprimer l'opportunité",
        "dialogText": "<b>Voulez vous vraiment supprimer cette offre d’emploi?</b> Si vous souhaitez la récupérer après coup, vous devrez communiquer avec l’équipe de soutien dans les 30 jours suivant sa suppression. Passé ce délai, l’offre d’emploi sera supprimée définitivement.",
        "cancel": "Annuler",
        "Retention": "Pour que le Carrefour d’emploi soit toujours à jour et pertinent, <strong>les possibilités d’emploi sont automatiquement supprimés six mois après la date limite de candidature.</strong> Nous vous recommandons donc d’en sauvegarder une copie pour vos dossiers",
        "emailSubject": "Demande de récupération d’une possibilité d’emploi supprimée dans le Carrefour de carrière",
        "classification": "Classification",
        "workSchedule": "Horaire de travail",
        "skills": "Compétences"
    }
});
